version: '3.8'

services:
  backend:
    container_name: backend
    image: node:lts-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      - postgres
    command: sh -c "npm install && npx prisma migrate dev && npm run dev"

  frontend:
    container_name: frontend
    image: node:lts-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "${FRONTEND_PORT}:5173"
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev"

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
